version: "3"  # optional since v1.27.0
services:
  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`35.193.216.219`)"
      - "traefik.http.routers.api.entrypoints=web"

  traefik:
    image: "traefik:v2.4"
    container_name: "traefikapi"
    command:
      #- "--log.level=DEBUG"git
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"